import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Registration Form',
    home: RegistrationForm(),
    debugShowCheckedModeBanner: false,
  ));
}

class RegistrationForm extends StatefulWidget {
  @override
  State<RegistrationForm> createState() => _RegistrationFormState();
}

class _RegistrationFormState extends State<RegistrationForm> {
  final _formKey = GlobalKey<FormState>();

  // Controllers for login, personal, and official details
  final emailController = TextEditingController();
  final passwordController = TextEditingController();
  final confirmPasswordController = TextEditingController();
  final firstNameController = TextEditingController();
  final middleNameController = TextEditingController();
  final lastNameController = TextEditingController();
  final mobileController = TextEditingController();
  final altMobileController = TextEditingController();
  final birthDateController = TextEditingController();
  final billNoController = TextEditingController(text: "0");
  final joiningDateController = TextEditingController();
  final cpfNoController = TextEditingController();
  final sapIdController = TextEditingController();

  // Controllers for bank details
  final accountNameController = TextEditingController();
  final accountNoController = TextEditingController();
  final bankNameController = TextEditingController();
  final branchController = TextEditingController();
  final ifscController = TextEditingController();

  // Controllers for nominee 1
  final nominee1NameController = TextEditingController();
  final nominee1DOBController = TextEditingController();

  // Controllers for nominee 2
  final nominee2NameController = TextEditingController();
  final nominee2DOBController = TextEditingController();

  // Controllers for current address
  final currentHouseController = TextEditingController();
  final currentLocalityController = TextEditingController();
  final currentLandmarkController = TextEditingController();
  final currentRoadController = TextEditingController();
  final currentAreaController = TextEditingController();
  final currentPostOfficeController = TextEditingController();
  final currentCityController = TextEditingController();
  final currentDistrictController = TextEditingController();
  final currentPincodeController = TextEditingController();

  // Controllers for permanent address
  final permanentHouseController = TextEditingController();
  final permanentLocalityController = TextEditingController();
  final permanentLandmarkController = TextEditingController();
  final permanentRoadController = TextEditingController();
  final permanentAreaController = TextEditingController();
  final permanentPostOfficeController = TextEditingController();
  final permanentCityController = TextEditingController();
  final permanentDistrictController = TextEditingController();
  final permanentPincodeController = TextEditingController();

  // Dropdown values
  String? gender, bloodGroup, designation, company, division;
  String? nominee1Relation, nominee2Relation;
  String? currentState, permanentState;

  bool isAddressSame = false;

  @override
  void dispose() {
    emailController.dispose();
    passwordController.dispose();
    confirmPasswordController.dispose();
    firstNameController.dispose();
    middleNameController.dispose();
    lastNameController.dispose();
    mobileController.dispose();
    altMobileController.dispose();
    birthDateController.dispose();
    billNoController.dispose();
    joiningDateController.dispose();
    cpfNoController.dispose();
    sapIdController.dispose();
    accountNameController.dispose();
    accountNoController.dispose();
    bankNameController.dispose();
    branchController.dispose();
    ifscController.dispose();
    nominee1NameController.dispose();
    nominee1DOBController.dispose();
    nominee2NameController.dispose();
    nominee2DOBController.dispose();
    currentHouseController.dispose();
    currentLocalityController.dispose();
    currentLandmarkController.dispose();
    currentRoadController.dispose();
    currentAreaController.dispose();
    currentPostOfficeController.dispose();
    currentCityController.dispose();
    currentDistrictController.dispose();
    currentPincodeController.dispose();
    permanentHouseController.dispose();
    permanentLocalityController.dispose();
    permanentLandmarkController.dispose();
    permanentRoadController.dispose();
    permanentAreaController.dispose();
    permanentPostOfficeController.dispose();
    permanentCityController.dispose();
    permanentDistrictController.dispose();
    permanentPincodeController.dispose();
    super.dispose();
  }

  void copyAddress() {
    permanentHouseController.text = currentHouseController.text;
    permanentLocalityController.text = currentLocalityController.text;
    permanentLandmarkController.text = currentLandmarkController.text;
    permanentRoadController.text = currentRoadController.text;
    permanentAreaController.text = currentAreaController.text;
    permanentPostOfficeController.text = currentPostOfficeController.text;
    permanentCityController.text = currentCityController.text;
    permanentDistrictController.text = currentDistrictController.text;
    permanentPincodeController.text = currentPincodeController.text;
    permanentState = currentState;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Registration Form')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              // Login
              sectionTitle("Login Details"),
              buildTextField(emailController, 'Email', true),
              buildPasswordField(passwordController, 'Enter Password'),
              buildPasswordField(confirmPasswordController, 'Confirm Password'),
              // Personal
              sectionTitle("Personal Details"),
              buildTextField(firstNameController, 'First Name', true),
              buildTextField(middleNameController, 'Middle Name', false),
              buildTextField(lastNameController, 'Last Name', true),
              buildDropdown("Gender", gender, ['Male', 'Female', 'Other'], (val) => setState(() => gender = val),isRequired: true),
              buildDropdown("Blood Group", bloodGroup, ['A+', 'B+', 'O+', 'AB+', 'A-', 'B-', 'O-', 'AB-'], (val) => setState(() => bloodGroup = val)),
              buildDropdown("Designation", designation, ['Junior Engineer(J. E.)','Assistant Engineer(A. E.)', 'Programmer(P)', 'System Analyst(S. A.)',
                'Deputy Executive Engineer(DY.E.E)','Executive Engineer(E. E.)','Superintendent Engineer(S. E.)',
                'Chief Engineer(C. E.)','Regional Director(R. D.)','Technical Member(T. M.)',
                'Deputy Chief Engineer(DY.C.E.)','Dy. Chief Engineer(Civil)(DY.C.E.(C))',
                'Executive Director(E. D.)','Add. Dy. Executive Engineer(ADD.DY.E.E)',
                'Additional Executive Engineer(ADD.E.E.)',
                'Assistant Programmer(A. P.)',], (val) => setState(() => designation = val), isRequired: true),
              buildTextField(mobileController, 'Mobile No.', true, keyboardType: TextInputType.phone),
              buildTextField(altMobileController, 'Alternate Mobile', false, keyboardType: TextInputType.phone),
              buildDateField(birthDateController, 'Birth Date (dd-mm-yyyy)', true),

              // Official
              sectionTitle("Official Details"),
              buildDropdown("Select Company", company, ['MSEB HOLDING CO', 'MSPGC LTD','MSETC LTD','MSEDC LTD','MSEB','TORRENT','MMRDA','MEDA'], (val) => setState(() => company = val), isRequired: true),
              buildDropdown("Division No.", division, [
                '1 -  NAGPUR	CHIEF ENGINEER	O & M	ZONE	VIDYUT BHAVAN	 KATOL ROAD	NAGPUR	440014',
                '2 -  NAGPUR	SUPTDG. ENGINEER	RURAL	CIRCLE	VIDYUT BHAVAN	KATOL ROAD	NAGPUR	440013',
                '3 -  NAGPUR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION TARSHA ROAD	MOUDA',

                '4 -  NAGPUR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION II	GANGA SADAN, WARD 3		BAZAR ROAD	SAONER',
                '5 -  NAGPUR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION		KATOL	',
                '6 -  BHANDARA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	VIDYUT BHAVAN	  NAGPUR ROAD	BHANDARA',
                '7 -  GONDIA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	OLD POWER HOUSE	RAM NAGAR		GONDIA' ,

                '8 - 	NAGPUR	SUPTDG. ENGINEER	TRANS (O AND M)	CIRCLE	VIDYUT BHAVAN		KATOL ROAD	NAGPUR	440013',
                '9 - 	NAGPUR	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	MOHOTA APART	CHAONI	KATOL ROAD	NAGPUR	440013',
                '10 -	BHANDARA	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	VIDYUT BHAVAN	 NAGPUR ROAD	BHANDARA	441904',
                '11 -  CHANDRAPUR	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	OLD POWER HOUSE		BALLARSHAH	442901',
                '12 -	NAGPUR	EXECUTIVE ENGINEER	TESTING	DIVISION	MANKAPUR	CHINDWADA ROAD	NAGPUR',
                '13 -	CHANDRAPUR	EXECUTIVE ENGINEER	TESTING	DIVISION	OLD POWER HOUSE		BALLARSHAH',
                '14 -	NAGPUR	EXECUTIVE ENGINEER	TELECOM	DIVISION	OLD POWER HOUSE AREA	MANKAPUR	KORADI ROAD	NAGPUR	',
                '15 -	NAGPUR	SUPTDG. ENGINEER	TESTING AND COM.	CIRCLE	G-8,NR BALJAGAT	LAXMINAGAR	NAGPUR	440022',
                '16 -	NAGPUR	SUPTDG. ENGINEER	LOAD DESPATCH	CENTRE	ATTWA MAIL	AMRAVATI ROAD	NAGPUR	440023',
                '17 -	WARDHA	SUPTDG. ENGINEER	O & M	CIRCLE	VIDYUT BHAVAN	 	BORGAON NAKA ROAD	WARDHA	',
                '18 -	WARDHA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	VIDYUT BHAVAN		BORGAON NAKA ROAD	WARDHA	',
                '19 -	WARDHA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	ARVI	442201',
                '20 -	WARDHA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	HINGANGHAT	',
                '21 -	CHANDRAPUR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	VIDYUT BHAVAN	BABUPETH	CHANDRAPUR',
                '22 - BULDHANA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	ADM.BLDG,	CHIKHALI ROAD	BULDHANA',
                '23 -	CHANDRAPUR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	WARORA',
                '24 - GADCHIROLI	EXECUTIVE ENGINEER	CONSTRUCTION	DIVISION GADCHIROLI',
                '25 -	GADCHIROLI	EXECUTIVE ENGINEER	C.C.O & M	DIVISION		GADCHIROLI',
                '26 -	GADCHIROLI	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	NR.PETROL PUMP	CHANDRAPUR ROAD	ALLAPALLI	442703',
                '27 -	NAGPUR	EXECUTIVE ENGINEER	400 KV LINES CONST	DIVISION	47,GANGA BUILDING	GOKULPETH		NAGPUR	',
                '28 -	NAGPUR	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	OLD POWER AREA	MANKAPUR	KORADI ROAD	NAGPUR	',
                '29 - CHANDRAPUR	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	G.C.R.BLDG	C.T.P.S COLONY	TADOBA ROAD	DURGAPUR',
                '30 -	JALGAON	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION		KHADKA	BHUSAWAL',
                '31 -	NAGPUR	CHIEF ENGINEER	400 KV CONST.	ZONE	48,GANGA BLDG.	GOKULPETH	  	NAGPUR		',
                '32 -	NAGPUR	SUPTDG. ENGINEER	400 KV LINES CONST	CIRCLE	P.NO.248	DHARAMPETH	CANAL ROAD	NAGPUR	',
                '33 -	CHANDRAPUR	EXECUTIVE ENGINEER	H.V.D.C.T.L 	DIVISION	TPS COMPLEX 	TADOBA ROAD	DURGAPUR	442404',
                '34 -	NAGPUR	SUPTDG. ENGINEER	EHVT CONSTRUCTION	CIRCLE	VIDYUT BHAVAN		KATOL ROAD	NAGPUR	440013',
                '35 -	NAGPUR	EXECUTIVE ENGINEER	EHVT LINES	DIVISION	VIDYUT BHAVAN	 	KATOL ROAD	NAGPUR	440013',
                '36 -	NAGPUR	EXECUTIVE ENGINEER	EHVT CIVIL CONST.	DIVISION	ARK 16U2,WARD NO 65	MOHAN NAGAR	KAMPTHEE ROAD	NAGPUR	440001',
                '37 -	AMRAVATI	EXECUTIVE ENGINEER	EHV PROJECT	DIVISION	PRAKASH SARITA A WIN	MORSHI ROAD	AMRAVATI	444603',
                '38 -	NAGPUR	SUPTDG. ENGINEER	URBAN	CIRCLE	PRAKASH BHAVAN	SADAR	LINK ROAD	NAGPUR	',
                '39 -	NAGPUR	EXECUTIVE ENGINEER	URBAN	DIVISION I	PRAKASH BHAVAN,	SADAR	LINK ROAD	NAGPUR',
                '40 - NAGPUR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	NR.RAMKRISHNA M	CONGRESS NAGAR	NAGPUR',
                '41 -	NAGPUR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	MAHAL DIVISION	OLD SHUKRAWARI	NAGPUR',
                '42 -	NAGPUR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	GANDHIBAG DIV.	CHAPRUNAGAR SQUARE	C.A.ROAD	NAGPUR	440008	',
                '43 -	NAGPUR	DY EXE.ENGINEER	REGIONAL VEHICLE WORKSHOP	CENTRE	220KV S/STN	MANKAPUR	CHINDWADA ROAD	NAGPUR		',
                '44 -	NAGPUR	SUPTDG. ENGINEER	STORES	CIRCLE	DR.JOSHI CLINC	RAMDASPETH	CANAL ROAD	NAGPUR	440010	MSPGC LTD.',
                '45 -	NAGPUR	ASSISTANT CONTROLLER	MAJOR STORE ( A )	DIVISION	PATNI BUILDING	GANDHIBAGH		NAGPUR		MSEB',
                '46 - NAGPUR	EXECUTIVE ENGINEER	MAJOR STORE ( A )	DIVISION	PRAKASH BHAVAN	SADAR	LINK ROAD	NAGPUR',
                '47 - NAGPUR	EXECUTIVE ENGINEER	MAJOR STORE ( A )	DIVISION	KTPS	KORADI COMPLEX	CHINDWADA ROAD	KORADI	441111',
                '48 - NAGPUR	EXECUTIVE ENGINEER	EHVT SUB-STN.CONST.	DIVISION	118 APP.FLOORA HOTEL	RAJIV NAGAR	WARDHA ROAD	NAGPUR	',
                '49 - NAGPUR	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	33 KV MODEL MILL S/S	GANESHPETH	NAGPUR	440018',
                '50 -	YEOTMAL	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	YEOTMAL		MSEB',
                '51 -	NAGPUR	DY.CHIEF ENGINEER	CIVIL CONSTRUCTION	CIRCLE KHAPERKHEDA	',
                '52 -	NAGPUR	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION II	KORADI COMPLEX	CHINDWADA ROAD	KORADI	441111',
                '53 -	NAGPUR	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION III	KORADI COMPLEX	CHINDWADA ROAD	KORADI	441111',
                '54 -	NAGPUR	CHIEF ENGINEER	GENERATION (CIVIL)	ZONE	GEN-II	KORADI COMPLEX	CHINDWADA ROAD	KORADI	441111',
                '55 -	NAGPUR	SUPTDG. ENGINEER	GENERATION ( PROJECT)	THERMAL POWER STATION	KHAPERKHEDA',
                '56 -	NAGPUR	DY.CHIEF ENGINEER	GENERATION ( PROJECT)	THERMAL POWER STATION	OFFICE COMPLEX	T.P.S.	KHAPERKHEDA	',
                '57 - NAGPUR	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION I		T.P.S.	KHAPERKHEDA',
                '58 -	NAGPUR	CHIEF ENGINEER	GENERATION (O & M)	THERMAL POWER STATION		T.P.S.	KHAPERKHEDA',
                '59 -	NAGPUR	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION II		T.P.S.	KHAPERKHEDA',
                '60 -	CHANDRAPUR	GENERAL MANAGER	CIVIL CONSTRUCTION	CIRCLE	NIRMAN BHAVN COMPLEX	CIVIL COMPLEX	TADOBA ROAD	DURGAPUR		',
                '61 -	CHANDRAPUR	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION I	OPP CHURCH BLDG	CIVIL COMPLEX	TADOBA ROAD',
                '62 -	CHANDRAPUR	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION II	OPP CHURCH BLDG	CIVIL COMPLEX	TADOBA ROAD	DURGAPUR',
                '63 -	CHANDRAPUR	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION III	OPP CHURCH BLDG	CIVIL COMPLEX	TADOBA ROAD	DURGAPUR',
                '64 -	CHANDRAPUR	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION IV	OPP CHURCH BLDG	CIVIL COMPLEX	TADOBA ROAD	DURGAPUR',
                '65 -	CHANDRAPUR	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION	D-V OP CHURCH CIVIL COMPLEX	TADOBA ROAD	DURGAPUR	',
                '66 -	NAGPUR	CHIEF ENGINEER	GENERATION (O & M)	THERMAL POWER STATION	KORADI COMPLEX	CHINDWADA ROAD	KORADI	441111',
                '67 -	CHANDRAPUR	CHIEF ENGINEER	GENERATION (O & M)	THERMAL POWER STATION	T.P.S.DURGAPUR	442404',
                '68 -	CHANDRAPUR	SUPTDG. ENGINEER	GENERATION (O & M)	THERMAL POWER STATION	T.P.S.BALLARSHAH	',
                '69 -	NAGPUR	CHIEF ENGINEER	TESTING & INSTRUMENTATION	ZONE	VIDYUT BHAVAN	  KATOL ROAD	NAGPUR	440013',
                '70 -	CHANDRAPUR	SUPTDG. ENGINEER	TRANS (O AND M)	CIRCLE	MADURWAR HOSP.	VIVEK NAGAR	MUL ROAD	CHANDRAPUR	442402',
                '71 -	DHULE	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	DAMODAR BLDG.	NEHRU NAGAR	 DEOPUR	424001',
                '72 -	MUMBAI	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	BRAHMAPUTRA  P.B.NO4	KALWA	THANE BELAPUR ROAD	MUMBAI	400708',
                '73 -	THANE	EXECUTIVE ENGINEER	TRANSMISSION LINES O & M	DIVISION	BOISAR (TQ PALGHAR)	 	TARAPUR	401501',
                '74 -	PUNE	EXECUTIVE ENGINEER	400 KV R.S.C.C	DIVISION	SAKET BUILDING	SADASHIV PETH		PUNE	411030	',
                '75 -	AMRAVATI	EXECUTIVE ENGINEER	RURAL	DIVISION	VIDYUT BHAVN	SHIVAJI NAGAR	 AMRAVATI	444602',
                '76 -	CHANDRAPUR	SUPTDG. ENGINEER	C.C.O & M	CIRCLE	VIDYUT BHAVAN	BABUPETH',
                '77 -	YEOTMAL	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	VIDYUT BHAVAN	 KARLA ROAD	PUSAD	445215',
                '78 - NASHIK	CHIEF ENGINEER	GENERATION (O & M)	THERMAL POWER STATION	EKLAHARE	NASHIK ROAD	422105',
                '79 - BULDHANA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION		OLD POWER HOUSE		KHAMGAON	444303',
                '80 -	MUMBAI	CHIEF ENGINEER	GENERATION ( PROJECT)	HEAD OFFICE	PRAKASHGAD,3 FLOOR	BANDRA (EAST)		MUMBAI	400051',
                '81 -	PUNE	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	PARVATI DN,220 KV SN	SINGHAGAD ROAD	PUNE	411030',
                '82 -	YEOTMAL	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	ADM BLDG	ARNI ROAD	YEOTMAL	',
                '83 -	AURANGABAD	EXECUTIVE ENGINEER	EHVT CIVIL CONST.	DIVISION	MATHRUCHAYA I FLOOR	MILL CORNER	KHADKESAWAR ROAD	AURANGABAD 431001',
                '84 -	NANDED	EXECUTIVE ENGINEER	O & M	DIVISION	VIDYUT BHAVAN	  BHOKAR	',
                '85 -	AKOLA	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	II FLOR,VIDYUTBHAVAN	RATANLAL PLOT	 AKOLA	444005',
                '86 -	NASHIK	DY.CHIEF ENGINEER	TRAINING	CENTRE	CHAMRI NO.1	EKLAHARE	 NASHIK ROAD	422105',
                '87 -	JALGAON	CHIEF ENGINEER	GENERATION (O & M)	THERMAL POWER STATION		DEEPNAGAR		BHUSAWAL	425307',
                '88 -	AKOLA	CHIEF ENGINEER	GENERATION (O & M)	THERMAL POWER STATION		VIDYUT NAGAR	PARAS	444109',
                '89 -	NAGPUR	CHIEF ENGINEER	TRAINING	CENTRE	D.O.T.	KORADI COMPLEX	CHINDWADA ROAD	KORADI	441111',
                '90 -	NASHIK	EXECUTIVE ENGINEER	O & M	DIVISION	RANG MAHAL HALL	 	CHANDWAD	423101',
                '91 -	THANE	EXECUTIVE ENGINEER	O & M	DIVISION	SIDDHIVINAYK COMPLEX	KALYAN (EAST)',
                '92 -	JALGAON	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION I	SHIVAJI NAGAR	WARANGAON ROAD	BHUSAWAL	425201',
                '93 -	JALGAON	DY EXE.ENGINEER	EHVT LINES	SUB DIVISION	KHARGAON ROAD	CHALISGAON',
                '94 -	WARDHA	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	VIDYUT BHAVAN	   	BORGAON NAKA ROAD	WARDHA	442001',
                '95 -	NAGPUR	EXECUTIVE ENGINEER	400 KV TESTING	DIVISION	MOHOTA APART	CHAONI	KATOL ROAD	NAGPUR	440013',
                '96 -	AMRAVATI	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	OLD POWER HOUSE		DAFRIN HOSPITAL ROAD	AMRAVATI	444609',
                '97 -	PALGHAR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	VIDYUT BHAVAN		MANOR ROAD	PALGHAR	401404',
                '98 -	NAGPUR	CHIEF ENGINEER	GENERATION ( PROJECT)	THERMAL POWER STATION	KORADI COMPLEX	CHINDWADA ROAD	KORADI	441111',
                '99 -	GADCHIROLI	EXECUTIVE ENGINEER	CONSTRUCTION	DIVISION	AHERI	',
                '100 -	PUNE	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	BLOCK NO.303	RASTA PETH	PUNE	411011',
                '101 -  NAGPUR	SUPTDG. ENGINEER	CONST.CUM MAINT.CIVIL	CIRCLE	VIDYUT BHAVAN	 	KATOL ROAD	NAGPUR	440013',
                '102 -	AMRAVATI	EXECUTIVE ENGINEER	EHVT LINES	DIVISION	OLD POWER HOUSE	 DAFRIN HOSPITAL ROAD	AMRAVATI	444609',
                '103 -	BHANDARA	SUPTDG. ENGINEER	O & M	CIRCLE	VIDYUT BHAVAN	 NAGPUR ROAD	BHANDARA',
                '104 -	AKOLA	CHIEF ENGINEER	RURAL	ZONE	VIDYUT BHAVAN	RATANLAL PLOT	 AKOLA	',
                '105 -	AURANGABAD	CHIEF ENGINEER	RURAL	ZONE	VIDYUT BHAVAN	 	DR.AMBEDKAR ROAD	AURANGABAD	431001',
                '106 -	AURANGABAD	EXECUTIVE ENGINEER	EHVT CIVIL CONST.	DIVISION	ADM.BLD.132 KV.S/S.	OLD POWER HOUSE	 	HARSUL	431001',
                '107 -	CHANDRAPUR	SUPTDG. ENGINEER	H.V.D.C.(R.S.C.)	CIRCLE	CTPS CAMPUS	 DURGAPUR	442404',
                '108 -	MUMBAI	EXECUTIVE ENGINEER	TESTING	DIVISION	SECTOR-I	WASHI	 MUMBAI	',
                '109 -	SOLAPUR	EXECUTIVE ENGINEER	URBAN	DIVISION	BIJLEE BHAVAN	URJA NAGAR	SOLAPUR	413001',
                '110 -	CHANDRAPUR	CHIEF ENGINEER	GENERATION (O & M)	THERMAL POWER STATION	500MW O&M	T.P.S.	DURGAPUR	',
                '111 -	NAGPUR	SUPTDG. ENGINEER	CIVIL CONSTRUCTION	CIRCLE	KORADI COMPLEX	CHINDWADA ROAD	KORADI	441111',
                '112 -	NASHIK	EXECUTIVE ENGINEER	RURAL	DIVISION	PATEL BUILDING	NEAR ZILLA PARISHAD	 NASHIK	',
                '113 -	AMRAVATI	EXECUTIVE ENGINEER	URBAN	DIVISION	NR.DAFRIN P.HOU		AMRAVATI',
                '114 -	PARLI	EXECUTIVE ENGINEER	CIVIL	DIVISION I		T.P.S.		PARLI-VAIJNATH		',
                '115 -	MUMBAI	CHIEF ENGINEER	CIVIL	ZONE	GEN-I,EST.BATT	MATUNGA	DHARAVI ROAD	MUMBAI	400019',
                '116 -	DHULE	EXECUTIVE ENGINEER	O & M	DIVISION	CEMENT POL FACTORY	NANDURBAR ROAD	DHONDAICHA	425408',
                '117 -	AURANGABAD	SUPTDG. ENGINEER	CIVIL CONSTRUCTION	CIRCLE	TANKASALE NAGAR	STATION ROAD	AURANGABAD',
                '118 -	RATNAGIRI	CHIEF ENGINEER	GENERATION (O & M)	HYDRO POWER STATION	KOYANA GEN STATION 	JAL VIDYUT KENDRA	 PHOPHALI	415601',
                '119 -	CHANDRAPUR	DY.CHIEF ENGINEER	GENERATION ( PROJECT)	THERMAL POWER STATION	TADOBA ROAD	DURGAPUR		',
                '120 -	JALGAON	EXECUTIVE ENGINEER	O & M	DIVISION	NR.RAILWAY STATION	GIRAD ROAD	PACHORA',
                '121 -	JALGAON	EXECUTIVE ENGINEER	MAJOR STORE ( A )	DIVISION DEEPNAGAR	BHUSAWAL',
                '122 -	THANE	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION PADGHE	421101	',
                '123 -	AKOLA	EXECUTIVE ENGINEER	O & M	DIVISION WASHIM	',
                '124 -	AKOLA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	WASHIM	444505',
                '125 -	MUMBAI	A.P.O GR-I/HR-III	TRANSMISSION PLANNING	HEAD OFFICE	G9,PRAKASHGAD	BANDRA (EAST)MUMBAI	400051	MSEB',
                '126 -	MUMBAI	A.P.O GR-I/HR-III	TRANSMISSION PLANNING	HEAD OFFICE	G9,PRAKASHGAD	BANDRA (EAST)	MUMBAI	400051',
                '127 -	NAGPUR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	PLOT57 SECT.G MEGDUT	M.I.D.C. AREA	 	BUTIBORI	',
                '128 -	CHANDRAPUR	EXECUTIVE ENGINEER	MAJOR STORE ( B )	DIVISION	CTPS	DURGAPUR	',
                '129 -	RAIGAD	CHIEF ENGINEER	GAS TURBINE POWER STATION	THERMAL POWER STATION	STAGE I OPERATI	URAN	400072',
                '130 -	DHULE	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	OLD POWER HOUSE	 SAKRI ROAD	DHULE		MSEB',
                '131 - 	AMRAVATI	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	VIDYUT BHAVAN	  AMRAVATI		',
                '132 -	JALGAON	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	P.O.BOX NO.29		BHADGAON ROAD	CHALISGAON',
                '133 -	PUNE	EXECUTIVE ENGINEER	O & M	DIVISION		RAJGURU NAGAR	 KHED	',
                '134 -	LATUR	ASSISTANT ENGINEER	CONST.CUM MAINT.CIVIL	SUB DIVISION	SARASWATINIVAS	SHYAM NAGAR		LATUR		',
                '135 -	DHULE	EXECUTIVE ENGINEER	400 KV R.S.C.C	DIVISION	P.NO.32	SNEH NAGAR	STATION ROAD	DHULE	424001',
                '136 -	BEED	CHIEF ENGINEER	GENERATION (O & M)	THERMAL POWER STATION	UNIT-4,UNIT-5		PARLI-VAIJNATH	431520',
                '137 -	AMRAVATI	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	MORSHI',
                '138 -	BEED	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	400KV		GIRVALI	',
                '139 -	AKOLA	SUPTDG. ENGINEER	O & M	CIRCLE	VIDYUT BHAVAN	  AKOLA	',
                '140 -	YEOTMAL	SUPTDG. ENGINEER	O & M	CIRCLE	VIDYUT BHAVAN	  YEOTMAL	',
                '141 -	AKOLA	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION		RATANLAL PLOT	AKOLA',
                '142 -	CHANDRAPUR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	OLD POWER HOUSE	 	BALLARSHAH',
                '143 -	NAGPUR	EXECUTIVE ENGINEER	TESTING	DIVISION	NUZ,PRAKASH BHAVAN	GADDIGODAM	LINK ROAD	NAGPUR',
                '144 -	DHULE	EXECUTIVE ENGINEER	400 KV LINES CONST	DIVISION	CHANDRAPRAKASH 	VIKAS COLONY	SAKRI ROAD	DHULE	424001',
                '145 -	AMRAVATI	EXECUTIVE ENGINEER	CIVIL	DIVISION	VIDYUT BHAVAN	AMRAVATI',
                '146 -	PUNE	EXECUTIVE ENGINEER	400 KV CONST.	DIVISION	925, KASBA PETH	OLD MARKET ROAD	PUNE	411011',
                '147 -	MUMBAI	EXECUTIVE ENGINEER	TRANSMISSION PLANNING	DEPARTMENT	220KV,5-F,PRAKASHGAD	BANDRA (EAST)		MUMBAI	400051',
                '148 -	AMRAVATI	EXECUTIVE ENGINEER	C.C.O & M	DIVISION ACHALPUR',
                '149 -	MUMBAI	CHIEF ENGINEER	LOAD DESPATCH	CENTRE	P.O.BOX:95	KALWA	THANE	',
                '150 -	JALGAON	CHIEF GEN.MANAGER	GENERATION ( PROJECT)	THERMAL POWER STATION	1X 660 M.W.NEW PROJ.	DEEPNAGAR		BHUSAWAL	425307	',
                '151 -	CHANDRAPUR	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION OLD POWER HOUSE	 BALLARSHAH	',
                '152 -	AURANGABAD	EXECUTIVE ENGINEER	URBAN	DIVISION I	NR.JUBALEE PARK	 AURANGABAD	431005',
                '153 -	AKOLA	EXECUTIVE ENGINEER	RURAL	DIVISION	NR 220KV OLD SS		GORAKSHAN ROAD	AKOLA	444001',
                '154 -	MUMBAI	EXECUTIVE ENGINEER	CIVIL	DIVISION	G-F,PRAKASHGAD	BANDRA (EAST)	 MUMBAI	400051',
                '155 -	OSMANABAD	EXECUTIVE ENGINEER	O & M	DIVISION	DIV-I,ADM.BLDG.	SOLAPUR ROAD	OSMANABAD	413501',
                '156 -	AKOLA	DY EXE.ENGINEER	CIVIL	DIVISION	PSC POLE FACTOR		RISOD ROAD	WASHIM	444505	MSEB',
                '157 -	MUMBAI	EXECUTIVE ENGINEER	S & I DIVISION	2-FL,MAHALAXMI LODGE	SHIVAJI PETH	KALYAN (WEST)	421301	MSETC LTD.',
                '158 -	MUMBAI	CHIEF ENGINEER	LOAD DESPATCH	CENTRE	SYSTEM S.DEPT	AIROLI	MUMBAI	400708	MSETC LTD.',
                '159 - 	MUMBAI	EXECUTIVE ENGINEER	400 KV CONST.	DEPARTMENT	P.B-6,NAKODA	AIROLI	THANE BELAPUR ROAD	MUMBAI	400708',
                '160 -	MUMBAI	EXECUTIVE ENGINEER	INFORMATION TECHNOLOGY	CENTRE	NERUL	WASHI		MUMBAI	MSEB HCLTD',
                '161 -	NASHIK	SUPTDG. ENGINEER	CIVIL CONSTRUCTION	CIRCLE		GANESH MARKET	DR.AMBEDKAR ROAD	NASHIK		MSEB',
                '162 - 	BEED	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION	DIV-IV	PARLI-VAIJNATH		MSPGC LTD.',
                '163 -	THANE	JOINT DIRECTOR	INFORMATION TECHNOLOGY	CENTRE	4FL.TEJSHREE BULD.	KARNIK ROAD	KALYAN (WEST)	421304	',
                '164 -	RAIGAD	SUPTDG. ENGINEER	O & M	CIRCLE	DIST.CO-OP BNK.	PEN		MSEDC LTD.',
                '165 -	AMRAVATI	EXECUTIVE ENGINEER	MAJOR STORE ( A )	DIVISION	MORSHI ROAD	AMRAVATI		MSEDC LTD.',
                '166 -	NAGPUR	EXECUTIVE ENGINEER	ESTATE MANAGEMENT	DIVISION	PRAKASH BHAVAN	SADAR	LINK ROAD	NAGPUR		MSEB HCLTD',
                '167 -	JALGAON	EXECUTIVE ENGINEER	O & M	DIVISION	SAVADA		MSEDC LTD.',
                '168 -	BULDHANA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	KRUSHI UTPAN SMITI B	MALKAPUR	443101	',
                '169 -	GONDIA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION		SAKOLI	',
                '170 -	AHMEDNAGAR	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	BABHALESHWAR 	413737',
                '171 -	PUNE	SUPTDG. ENGINEER	CIVIL	CIRCLE	NR.MAHASABA GATE	SHIVAJI NAGAR	GANESH KHIND ROAD	PUNE	411016',
                '172 -	NASHIK	EXECUTIVE ENGINEER	URBAN	DIVISION	VANI COMPLEX	MUMBAI AGRA ROAD	NASHIK',
                '173 -	TAMILNADU	EXECUTIVE ENGINEER	TRAINING	DEPARTMENT	14/21,N.POWER T.INST	NAYVELI	607803	MSEDC LTD.',
                '174 -	NAGPUR	EXECUTIVE ENGINEER	MAJOR STORE ( B )	DIVISION		T.P.S.	KHAPERKHEDA		MSPGC LTD.',
                '175 -	YEOTMAL	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	SURANA GIN.COMP	 PANDARKAWADA.',
                '176 -	RAIGAD	EXECUTIVE ENGINEER	RURAL	DIVISION	PB-119 BHINGARI	VIDYUT NAGAR	PANVEL- PUNE HIGHWAY	PANVEL	410206',
                '177 -  BEED	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	ADM BUILDING	   	JALNA ROAD	BEED	431122',
                '178 -	PUNE	EXECUTIVE ENGINEER	H.V.D.C.	DIVISION	500KV,SHELAR BL	RAVIVAR PETH	UNNAR	',
                '179 -	MUMBAI	SUPTDG. ENGINEER	CONST.CUM MAINT.CIVIL	CIRCLE	D.DAS V.DAS BLD	 STATION ROAD	KALYAN (WEST)	421301',
                '180 -	NASHIK	SUPTDG. ENGINEER	TESTING & INSTRUMENTATION	THERMAL POWER STATION	EKLAHARE	   	NASHIK	',
                '181 -	MUMBAI	CHIEF ENGINEER	H.V.D.C.LINES CONST.	ZONE	CLD COMPOUND	AIROLI	THANE BELAPUR ROAD	MUMBAI	400708',
                '182 -	PARBHANI	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	VIDYUT BAHVAN	 JINTUR ROAD	PARBHANI	431401',
                '183 -	THANE	EXECUTIVE ENGINEER	H.V.D.C. CIVIL	DIVISION	PADGHE',
                '184 -	PUNE	EXECUTIVE ENGINEER	400 KV LINES CONST	DIVISION	1 ST FL,935	KASBA PETH	PUNE	411011	MSEB HCLTD',
                '185 -	THANE	EXECUTIVE ENGINEER	O & M	DIVISION	18,WAGHALE ESTATE	  THANE	4	MSEDC LTD.',
                '186 -	NASHIK	EXECUTIVE ENGINEER	TELECOM	DIVISION	NR.ANIRUDDHA TA	  NASHIK	422101',
                '187 -	CHANDRAPUR	CHIEF ENGINEER	GENERATION (O & M)	ZONE	CIVIL MAINT.UNIT	CHANDRAPUR',
                '188 -	THANE	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	TEJASHREE BLDG	JAHANGIR MAIDAN	KARNIK ROAD	KALYAN (WEST)	421301',
                '189 -	JALNA	EXECUTIVE ENGINEER	H.V.D.C.LINES CONST.	DIVISION	JALNA	',
                '190 -	OSMANABAD	EXECUTIVE ENGINEER	EHVT LINES	DIVISION	KANCHAN BUILDING	 OSMANABAD	',
                '191 -	CHANDRAPUR	SUPTDG. ENGINEER	H.V.D.C.	CIRCLE	VIDYUT BHAVAN		CHANDRAPUR',
                '192 -	MUMBAI	EXECUTIVE ENGINEER	ESTATE MANAGEMENT	DIVISION	P.NO-1	ESTRELLA BATTERIES	DHARAVI ROAD	MUMBAI	400019	MSEB HCLTD',
                '193 -	DHULE	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	AT POST KUNDANE		DHULE	424301',
                '194 -	THANE	EXECUTIVE ENGINEER	O & M	DIVISION	OPP.SAI MANDIR	RAMDAS NAGAR	VASAI(EAST)	401210',
                '195 -	AURANGABAD	EXECUTIVE ENGINEER	RURAL	DIVISION	APP.GARWARE STADIUM	CHIKALTHANA	NAREGAON ROAD	AURANGABAD	431001	MSEDC LTD.',
                '196 -	YEOTMAL	EXECUTIVE ENGINEER	TESTING	DIVISION	ARNI ROAD	YEOTMAL	',
                '197 -	MUMBAI	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	P.NO-5	AIROLI	THANE BELAPUR ROAD	MUMBAI	400708',
                '198 -	MUMBAI	EXECUTIVE ENGINEER	400 KV LINES CONST	DIVISION	P.B.NO.20	AIROLI	THANE BELAPUR ROAD	MUMBAI	400708',
                '199 -	JALGAON	SUPTDG. ENGINEER	O & M	CIRCLE	EDP,VIDYUTBHAVA	M.I.D.C. AREA	 JALGAON	',
                '200 -	OSMANABAD	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	CHAPNE BUILDIN	ANAND NAGAR		OSMANABAD',
                '201 -	NASHIK	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	OLD MAJOR STORE	HANUMAN NAGAR	JAIL ROAD	NASHIK ROAD	422101',
                '202 -	AMRAVATI	SUPTDG. ENGINEER	O & M	CIRCLE	VIDYUTBHAVAN	SHIVAJI NAGAR	AMRAVATI',
                '203 -	NAGPUR	JOINT DIRECTOR	INFORMATION TECHNOLOGY	CENTRE	VIDYUTBHAVAN	KATOL ROAD	NAGPUR	440013',
                '204 -	NAGPUR	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION	T.P.S.	KHAPERKHEDA',
                '205 -	PUNE	SUPTDG. ENGINEER	TESTING AND COM.	CIRCLE	403 IIIFL,ADM BUILD	RASTA PETH	PUNE	411011',
                '206 -	PUNE	EXECUTIVE ENGINEER	TESTING	DIVISION	GR.FLOOR 110 URBAN,	RASTA PETH	PUNE	411011',
                '207 -	CHANDRAPUR	EXECUTIVE ENGINEER	O & M	DIVISION	33 KV S/S.DELALWADI,		BRAMHAPURI',
                '208 -	PUNE	EXECUTIVE ENGINEER	TESTING	HYDRO POWER STATION	ADM.BUILDING	RASTA PETH	PUNE	411011	',
                '209 -	THANE	SUPTDG. ENGINEER	O & M	CIRCLE	TEJESHRI,3-FL	KALYAN (WEST)	KARNIK ROAD	KALYAN (WEST)	',
                '210 - 	RAIGAD	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	TAPKA COLONY	PANVEL	410206',
                '211 -	MUMBAI	SUPTDG. ENGINEER	TRANS (O AND M)	CIRCLE	MSEB COMPLEX PB.NO-3	AIROLI	THANE BELAPUR ROAD	NAVI  MUMBAI	400708',
                '212 -	NAGPUR	SUPTDG. ENGINEER	COAL PROCUREMENT	UNIT	VIDYUT BHAVAN		KATOL ROAD	NAGPUR	440013	',
                '213 -	NASHIK	EXECUTIVE ENGINEER	URBAN	DIVISION	U&R DN,MOTIBHAV	 	MALEGAON',
                '214 -	MUMBAI	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	BHANDUP	LAL BAHADUR SHASTRI 	MUMBAI	400078',
                '215 -	MUMBAI	SUPTDG. ENGINEER	EHV CONSTRUCTION	CIRCLE	SEC-17,P.B.NO-9	AIROLI	THANE BELAPUR ROAD	MUMBAI	400708	',
                '216 -	MUMBAI	SUPTDG. ENGINEER	ESTATE MANAGEMENT	DIVISION	GR-F,PRAKASHGAD	BANDRA (EAST)	MUMBAI	400051	MSEB HCLTD',
                '217 -	JALGAON	EXECUTIVE ENGINEER	C.C.O & M	DIVISION DHARANGAON	.',
                '218 -	RATNAGIRI	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	PIMPLI (BK)	415605	MSETC LTD.',
                '219 -	BULDHANA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	MALKAPUR MSEDC LTD.',
                '220 -	THANE	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	220KV S/S	BOISAR	SARAVALI	401501	MSETC LTD.',
                '221 -	JALGAON	EXECUTIVE ENGINEER	C.C.O & M	DIVISION DHARANGAON	MSEDC LTD.',
                '222 -	YEOTMAL	EXECUTIVE ENGINEER	CIVIL	DIVISION	VIDYUTBHAVAN	YEOTMAL		MSEB',
                '223 -	GADCHIROLI	SUPTDG. ENGINEER	O & M	CIRCLE	GADCHIROLI	MSEDC LTD.',
                '224 -	MUMBAI	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION	VIDYUT BAHVAN	BHANDUP	LAL BAHADUR SHASTRI 	MUMBAI	400078	MSEB',
                '225 -	PUNE	EXECUTIVE ENGINEER	GENERATION ( PROJECT)	HYDRO POWER STATION		PANSHET	412107	MSPGC LTD.',
                '226 -	NASHIK	EXECUTIVE ENGINEER	EHVT CONSTRUCTION	DIVISION	SHARMA BLDG.	TILAK ROAD	NASHIK		MSETC LTD.',
                '227 -	THANE	EXECUTIVE ENGINEER	O & M	DIVISION	C.SHIVAJI HOSPITAL	KALWA	THANE BELAPUR ROAD	THANE	400708	',
                '228 -	BEED	EXECUTIVE ENGINEER	EHVT LINES	DIVISION	MANIK COMPLEX	VIDYA NAGAR	   	BEED	431122	MSETC LTD.',
                '229 -	RATNAGIRI	CHIEF ENGINEER	O & M	ZONE	KONKAN ZONE		NUCHANE ROAD	RATNAGIRI		MSEDC LTD.',
                '230 -	JALGAON	EXECUTIVE ENGINEER	O & M	DIVISION	URBAN CUM RURAL	TAPI NAGAR	BHUSAWAL	425201	MSEDC LTD.',
                '231 -	PUNE	ASSISTANT ENGINEER	CENTRAL FABRICATION	DIVISION	PHURSUNGI		MSEB',
                '232 -	MUMBAI	EXECUTIVE ENGINEER	R.S.& T	DIVISION	BUZ, VIDYUT BHAVAN	BHANDUP	LAL BAHADUR SHASTRI 	MUMBAI	400078',
                '233 -	JALGAON	EXECUTIVE ENGINEER	TESTING	DIVISION	VIDYUT BHAVAN	  JALGAON	',
                '234 -	RATNAGIRI	SUPTDG. ENGINEER	O & M	CIRCLE	ADM.BUILDING.	OLD POWER HOUSE	NUCHANE ROAD	RATNAGIRI	415639',
                '235 -	MUMBAI	CHIEF ENGINEER	URBAN	ZONE	VIDYUT BHAVAN	BHANDUP	L.B.S.ROAD	MUMBAI	400078',
                '236 -	RAIGAD	EXECUTIVE ENGINEER	GENERATION (CIVIL)	HYDRO POWER STATION	TAILROL P.S.RAWALJI 	410205	MSPGC LTD.',
                '237 -	THANE	SUPTDG. ENGINEER	H.V.D.C.(R.S.C.)	CIRCLE	PADGHE		MSETC LTD.',
                '238 -	PUNE	EXECUTIVE ENGINEER	URBAN	DIVISION	BAND GARDEN DIVISION	NEAR BISHOP S SCHOOL	EXHIBITION ROAD	PUNE	411001',
                '239 -	MUMBAI	DY EXE.ENGINEER	REGIONAL VEHICLE WORKSHOP	CENTRE	BHANDUP	LAL BAHADUR SHASTRI 	MUMBAI	400078	MSEDC LTD.',
                '240 -	SATARA	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	ADM.BUILDING.	VISHRAMBAGH		SANGLI	416415',
                '241 -	MUMBAI	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	S-17,PO-28	KALWA	THANE BELAPUR ROAD	MUMBAI	400708	',
                '242 -	MUMBAI	EXECUTIVE ENGINEER	EHVT LINES	DIVISION	D-II,TEJASRI BLDG	JAHANGIR MAIDAN	KARNIK ROAD	KALYAN (WEST)	421301',
                '243 -	MUMBAI	EXECUTIVE ENGINEER	TELECOM	DIVISION	AIROLI	THANE BELAPUR ROAD	MUMBAI	400708	',
                '244 -	AURANGABAD	EXECUTIVE ENGINEER	400 KV CONST.	DIVISION	12 SUMITRA 	BHAGYA NAGAR	AURANGABAD	431001	MSEB HCLTD',
                '245 -	PUNE	CHIEF ENGINEER	EHVT CONSTRUCTION	ZONE	404	RASTA PETH		PUNE	',
                '246 -	RAIGAD	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	NAGOTHANE	PIPE NAGAR	KANSAI	402126	MSETC LTD.',
                '247 -	RAIGAD	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	29,BHIRWADI	M.I.D.C. AREA	  	MAHAD	402302	MSETC LTD.',
                '248 -	AKOLA	SUPTDG. ENGINEER	CIVIL	CIRCLE	VIDYUT BHAVAN	RATANLAL PLOT	 AKOLA	MSETC LTD.',
                '249 -	AKOLA	EXECUTIVE ENGINEER	URBAN	DIVISION	VIDYUT BHAVAN	RATANLAL PLOT		AKOLA		',
                '250 -	NANDURBAR	EXECUTIVE ENGINEER	O & M	DIVISION KUKADEL	OLD PRAKASHA ROAD	SHAHADA	425409',
                '251 -	MUMBAI	EXECUTIVE ENGINEER	O & M	DIVISION	SECTOR-5	WASHI	MUMBAI',
                '252 -	SATARA	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	ADMN.BLD.POST.SUPANE	VIJAY NAGAR STATION ROAD KARAD	415114',
                '253 -	MUMBAI	SUPTDG. ENGINEER	O & M	CIRCLE	PLOT-5 SECT-17	WASHI	   	NAVI  MUMBAI	400705	',
                '254 -	SATARA	EXECUTIVE ENGINEER	400 KV LINES CONST	DIVISION	MANIK SABHAGRUH	BUDHWARPETH	 KARAD	415110	',
                '255 -	BEED	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	BEED		',
                '256 -	RATNAGIRI	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	NR.ADM BLDG.1-F		RATNAGIRI	415639	',
                '257 -	AURANGABAD	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	MILK CORNER	OLD POWER HOUSE	DR.AMBEDKAR ROAD	AURANGABAD	431001	',
                '258 -	PARBHANI	EXECUTIVE ENGINEER	GENERATION ( PROJECT)	HYDRO POWER STATION	YELDARI	431510	MSPGC LTD.',
                '259 -	NASHIK	EXECUTIVE ENGINEER	GENERATION (O & M)	HYDRO POWER STATION	VAITARNA JAL V.		VAITARNANAGAR		MSPGC LTD.',
                '260 -	SANGLI	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	VISHRAMBAGH	SANGLI 	MSEB',
                '261 -	RAIGAD	EXECUTIVE ENGINEER	400 KV LINES CONST	DIVISION	NR.33KV S/STN	KUMBHAR KHIND	 	MAHAD		MSEB HCLTD',
                '262 -	DHULE	EXECUTIVE ENGINEER	TESTING	DIVISION	CHANDRAKOR	MANISH NAGAR	BHOKAR ROAD	DEOPUR	424001	',
                '263 -	JALGAON	EXECUTIVE ENGINEER	EHVT CIVIL CONST.	DIVISION	MANDORE BHAVAN	ZILLA PETH	DR.AMBEDKAR BHAVAN	JALGAON		MSETC LTD.',
                '264 -	THANE	EXECUTIVE ENGINEER	O & M	DIVISION	DIV-II,SHANTI CHAMBE	ULHAS NAGAR	M.G.ROAD	AMBARNATH	',
                '265 -	OSMANABAD	SUPTDG. ENGINEER	O & M	CIRCLE	ADM BLDG.	SOLAPUR ROAD	OSMANABAD		MSEDC LTD.',
                '266 -	RATNAGIRI	EXECUTIVE ENGINEER	O & M	DIVISION	NACHANE ROAD	RATNAGIRI		MSEDC LTD.',
                '267 -	PUNE	EXECUTIVE ENGINEER	CIVIL	DIVISION	NR.132 KV S/S 	BHIGWAN ROAD	BARAMATI	413102	MSEDC LTD.',
                '268 -	RAIGAD	EXECUTIVE ENGINEER	URBAN	DIVISION		BHINGARI	MUMBAI PUNE HIGHWAY	PANVEL		MSEDC LTD.',
                '269 -	SINDHUDURG	EXECUTIVE ENGINEER	O & M	DIVISION	M.I.D.C. AREA	VENGURLA ROAD	KUDAL	416520	MSEDC LTD.',
                '270 -	AURANGABAD	SUPTDG. ENGINEER	CONST.CUM MAINT.CIVIL	CIRCLE	SHAKTISAHKAR BL	SAMARTH NAGAR	   	AURANGABAD		MSEB',
                '271 -	NASHIK	EXECUTIVE ENGINEER	MAJOR STORE A	DIVISION	SAIKHEDA	 JAIL ROAD	NASHIKMSEDC LTD.',
                '272 -	PUNE	EXECUTIVE ENGINEER	URBAN	ZONE	ROOM NO 103,PUZ	RASTA PETH	PUNE	411011	MSEDC LTD.',
                '273 -	PUNE	CHIEF ENGINEER	URBAN	ZONE	BLOCK NO.208	RASTA PETH	PUNE		MSEDC LTD.',
                '274 -	PUNE	EXECUTIVE ENGINEER	400 KV R.S.C.C	ZONE	925,4-FL,ADM.BL	KASBA PETH	BAZAR ROAD	PUNE	411011	MSETC LTD.',
                '275 -	THANE	EXECUTIVE ENGINEER	O & M	DIVISION	TEJSHREE COMPLEX	JAHANGIR MAIDAN	KARNIK ROAD	KALYAN (WEST)	421301	MSEDC LTD.',
                '276 -	KOLHAPUR	EXECUTIVE ENGINEER	GENERATION (O & M)	HYDRO POWER STATION		TILLARI	416527	MSPGC LTD.',
                '277 -	AHMEDNAGAR	EXECUTIVE ENGINEER	URBAN	DIVISION	U&R DN,VIDYUTBHAVAN	 	AHMEDNAGAR		MSEDC LTD.',
                '278 -	MUMBAI	EXECUTIVE ENGINEER	TESTING	DIVISION		AIROLI		MUMBAI	MSEDC LTD.',
                '279 -	RATNAGIRI	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	VIDYUTBHAVAN	M.I.D.C. AREA	MIRJOLE ROAD	RATNAGIRI	415639	MSETC LTD.',
                '280 -	MUMBAI	SUPTDG. ENGINEER	TRANS (O AND M)	DIVISION	P.B.NO-4,KALWA	AIROLI	THANE BELAPUR ROAD	MUMBAI	400708	MSETC LTD.',
                '281 -	MUMBAI	CHIEF ENGINEER	H.V.D.C.	ZONE	4-F,SECTOR-17	WASHI		NAVI  MUMBAI	400703	MSETC LTD.',
                '282 -	THANE	EXECUTIVE ENGINEER	O & M	DIVISION	DI-I,SINGANI BL	ULHAS NAGAR		THANE		MSEDC LTD.',
                '283 -	KOLHAPUR	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	VIDYUT BHAVAN	 KOLHAPUR		MSETC LTD.',
                '284 -	PUNE	SUPTDG. ENGINEER	RURAL	CIRCLE	TESTING DN.BLOCK 126	RASTA PETH	PUNE	411011	MSEDC LTD.',
                '285 -	RAIGAD	SUPTDG. ENGINEER	TRANS (O AND M)	CIRCLE	TAKKA COLONY	OLD MUMBAI PUNE ROAD	PANVEL	410206	MSETC LTD.',
                '286 -	SOLAPUR	EXECUTIVE ENGINEER	CONSTRUCTION	DIVISION PANDHARPUR		MSEDC LTD.',
                '287 -	JALGAON	SUPTDG. ENGINEER	TRANS (O AND M)	CIRCLE	NR BOI,SAWKAR BLDG	KHADKA	JAMNER ROAD	BHUSAWAL	MSETC LTD.',
                '288 -	PUNE	EXECUTIVE ENGINEER	O & M	DIVISION	ADM.BLDG,G.FL	RASTA PETH	PUNE	MSEDC LTD.',
                '289 -	AKOLA	EXECUTIVE ENGINEER	TESTING	DIVISION	GORAKSHAN ROAD	AKOLA	MSEDC LTD.',
                '290 -	SATARA	EXECUTIVE ENGINEER	O & M	DIVISION	PHALTAN		MSEDC LTD.',
                '291 -	THANE	SUPTDG. ENGINEER	O & M	CIRCLE	2/3 DEEPSHRI BLDG	VASAI ROAD	VASAI(EAST)	401210	MSEDC LTD.',
                '292 -	AKOLA	DY EXE.ENGINEER	MAJOR STORE B	DIVISION	T.P.S.	PADAMPURA STN.ROAD	PARAS	MSPGC LTD.',
                '293 -	MUMBAI	EXECUTIVE ENGINEER	TESTING	DIVISION	AIROLI-NODE	KALWA	THANE BELAPUR ROAD	NAVI  MUMBAI	400708	MSEDC LTD.',
                '294 -	PUNE	SUPTDG. ENGINEER	TRANS (O AND M)	CIRCLE	BL 404,ADM BLD	RASTA PETH	 PUNE	411011	MSETC LTD.',
                '295 -	SOLAPUR	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	NEAR RANG BVN	 SOLAPUR	MSEB',
                '296 -	NASHIK	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	1FLOOR,BLOCK 7	SHIDDESHWAR NAGAR	JAIL ROAD	NASHIK ROAD	422101	MSETC LTD.',
                '297 -	BEED	EXECUTIVE ENGINEER	MAJOR STORE( B )	DIVISION	T.P.S.	PARLI-VAIJNATH	MSPGC LTD.',
                '298 -	NANDED	EXECUTIVE ENGINEER	MAJOR STORE ( A )	DIVISION	NANDED	MSEDC LTD.',
                '299 -	THANE	EXECUTIVE ENGINEER	MAJOR STORE (A)	DIVISION	TEJASHREE	JAHANGIR MAIDAN	KARNIK ROAD	KALYAN (WEST)',
                '300 -	NASHIK	CHIEF ENGINEER	O & M	ZONE	VIDHYUT BHAVAN	NASHIK ROAD	MSEDC LTD.',
                '301 -	THANE	SUPTDG. ENGINEER	O & M	CIRCLE	BHIWANDI	MSEDC LTD.',
                '302 -	SOLAPUR	SUPTDG. ENGINEER	O & M	CIRCLE	JUNI MILL COMPOUND	URJA NAGAR SOLAPUR	413001	MSEDC LTD.',
                '303 -	SOLAPUR	EXECUTIVE ENGINEER	O & M	DIVISION	NR.P.C.C.POL FACTORY	LINK ROAD	PANDHARPUR	413304	MSEDC LTD.',
                '304 -	PUNE	EXECUTIVE ENGINEER	O & M	DIVISION	MSEB BARAMATI		MSEDC LTD.',
                '305 -	NASHIK	EXECUTIVE ENGINEER	URBAN	DIVISION	MSEB,D1,VIDHYUT  BVN	 NASHIK ROAD		MSEDC LTD.',
                '306 -	JALGAON	EXECUTIVE ENGINEER	O & M	DIVISION	MSEB	CHALISGAON	424101	MSEDC LTD.',
                '307 -	SOLAPUR	EXECUTIVE ENGINEER	O & M	DIVISION	MSEB,KHANDELWAL BLD		BARSHI		MSEDC LTD.',
                '308 -	BULDHANA	SUPTDG. ENGINEER	O & M	CIRCLE	MSEB,ADM BLDG	CHIKHALI ROAD	BULDHANA	MSEDC LTD.',
                '309 -	NASHIK	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION	I,MSEB ,OLD C-17/18 	EKLAHARE	NASHIK ROAD		MSEB',
                '310 -	BULDHANA	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	VIDYUT BHAVAN	CHIKHALI ROAD	BULDHANA	443001	MSETC LTD.',
                '311 -	SATARA	EXECUTIVE ENGINEER	EHVT SUB-STN.CONST.	DIVISION	MSEB 	SANGLI	MSETC LTD.',
                '312 -	AURANGABAD	EXECUTIVE ENGINEER	MAJOR STORE (A)	DIVISION	220 K.V. S/ST.	PADEGAON	431002	MSETC LTD.',
                '313 -	THANE	EXECUTIVE ENGINEER	O & M	DIVISION	MSEB,DIVISION II	BHIWANDI		MSEDC LTD.',
                '314 -	PUNE	EXECUTIVE ENGINEER	400 KV CONST.	DIVISION	MSEB,TRANS.CUM CONS 	KASBA PETH	PUNE	MSEB HCLTD',
                '315 -	NANDED	EXECUTIVE ENGINEER	RURAL	DIVISION	MAJOR STORE BUILDING	TARODA NAKA	PURNA ROAD	NANDED	431605	MSEDC LTD.',
                '316 -	PUNE	SUPTDG. ENGINEER	STORES	CIRCLE	ADM BLDG, BLOCK-112 	RASTA PETH	PUNE	411011	MSEDC LTD.',
                '317 -	PUNE	EXECUTIVE ENGINEER	URBAN	DIVISION	MSEB KOTHRUD DN	SNDT COLLEGE	KARVE ROAD	PUNE	MSEDC LTD.',
                '318 -	THANE	EXECUTIVE ENGINEER	O & M	DIVISION	MSEB 	ULHAS NAGAR		THANE		MSEDC LTD.',
                '319 -	BEED	EXECUTIVE ENGINEER	CIVIL	DIVISION II	V, T.P.S. MSEB 	PARLI-VAIJNATH	MSPGC LTD.',
                '320 -	BEED	SUPTDG. ENGINEER	CIVIL	CIRCLE	T.P.S.MSEB	PARLI-VAIJNATH	MSPGC LTD.',
                '321 -	LATUR	EXECUTIVE ENGINEER	EHVT CONSTRUCTION	DIVISION	MSEB ,VIDHYUT BHAVAN	LATUR		MSETC LTD.',
                '322 -	DHULE	EXECUTIVE ENGINEER	URBAN	DIVISION	MSEB,OLD POWER HOUSE	SAKRI ROAD	DHULE	424001	MSEDC LTD.',
                '323 -	PUNE	SUPTDG. ENGINEER	HYDRO POWER STATION	CIRCLE	925	KASBA PETH	PUNE	411011	MSPGC LTD.',
                '324 -	SINDHUDURG	SUPTDG. ENGINEER	O & M	CIRCLE	MSEB ,VIDHYUT BHAVAN	M.I.D.C. AREA		KUDAL	416520	MSEDC LTD.',
                '325 -	HINGOLI	EXECUTIVE ENGINEER	O & M	DIVISION	MSEB 	HINGOLI		MSEDC LTD.',
                '326 -	RAIGAD	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	MSEB,	GOREGAON	402103	MSEDC LTD.',
                '327 -	THANE	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	MSEB ,182/18	M.E.S.B.COLONY	VASAI ROAD	VIRAR	MSEDC LTD.',
                '328 -	SATARA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	MSEB,VIDYUT BHAVAN	KARAD		MSEDC LTD.',
                '329 -	AHMEDNAGAR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	SHINDE BHAVAN	VIDYA NAGAR	SANGAMNER	422605	MSEDC LTD.',
                '330 -	JALGAON	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	PL.NO.03 	M.I.D.C. AREA	AJINTHA ROAD	JALGAON	425003	MSEDC LTD.',
                '331 -	BEED	CHIEF ENGINEER	GENERATION ( PROJECT)	DIVISION	MSEB ,ADM BLDG	T.P.S.PARLI-VAIJNATH	431520	MSPGC LTD.',
                '332 -	LATUR	EXECUTIVE ENGINEER	O & M	DIVISION	SALE GALLI	OLD POWER HOUSE	BIDAR ROAD	UDGIR	413512	MSEDC LTD.',
                '333 -	NASHIK	EXECUTIVE ENGINEER	TESTING	DIVISION	MSEB VIDYUT BHAVAN	NASHIK ROAD	MSETC LTD.',
                '334 -	RAIGAD	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	MSEB  SECTOR 6	KHARGHAR	PANVEL	410210	MSETC LTD.',
                '335 -	LATUR	EXECUTIVE ENGINEER	O & M	DIVISION	VIDYUT BHAVAN	SALE GALLI	LATUR	413512	MSEDC LTD.',
                '336 -	SANGLI	EXECUTIVE ENGINEER	TESTING	DIVISION	MSEB 	VISHRAMBAGH		SANGLI 	416415	MSEDC LTD.',
                '337 -	RAIGAD	EXECUTIVE ENGINEER	GENERATION (O & M)	HYDRO POWER STATION	BHIRA H.P.S.VIA PALI	RAWALJI 410205',
                '338 -	NANDED	SUPTDG. ENGINEER	O & M	CIRCLE	MSEB,VIDYUT BHAVAN 	ANNABHAU SATHE SQ	NANDED',
                '339 -	BEED	EXECUTIVE ENGINEER	O & M	DIVISION	NR.33 KV.S.S.	AMBEJOGAI	431517',
                '340 -	AHMEDNAGAR	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	MSEB PIMPRI NIRMAL 		BABHALESHWAR 	423107',
                '341 -	THANE	EXECUTIVE ENGINEER	O & M	DIVISION I	MIDC NR. PASSPORT  WAGLE ESTATE	ROAD NO 16	THANE	400604',
                '342 -	JALGAON	EXECUTIVE ENGINEER	URBAN	DIVISION	MSEB UCR DN NR.MATAN	ZILLA PETH	JALGAON	',
                '343 -	PUNE	EXECUTIVE ENGINEER	URBAN	DIVISION	MSEB PADMAVATI DN VIVEKANAND STATUE	PUNE-SATARA ROAD	PUNE	411037',
                '344 -	PUNE	EXECUTIVE ENGINEER	URBAN	DIVISION	NAGAR ROAD  DN.	PUNE',
                '345 -	AKOLA	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION I	MSEB TPS PARAS	VIDYUT NAGAR	PARAS	444109',
                '346 -	AKOLA	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION II	MSEB TPS PARAS 	VIDYUT NAGAR	PARAS	444109',
                '347 -	AKOLA	GENERAL MANAGER	CIVIL CONSTRUCTION	CIRCLE	MSEB TPS PARAS 	VIDYUT NAGAR PARAS	444109',
                '348 -	AKOLA	SUPTDG. ENGINEER	GENERATION ( PROJECT)	THERMAL POWER STATION	MSEB  T.P.S. PARAS	PARAS	444109',
                '349 -	AMRAVATI	SUPTDG. ENGINEER	TRANS (O AND M)	CIRCLE	MSEB 	AMRAVATI		',
                '350 -	PUNE	EXECUTIVE ENGINEER	O & M	DIVISION	MSEB RAJGURUNAGAR	 PUNE	',
                '351 -	AURANGABAD	EXECUTIVE ENGINEER	400 KV R.S.C.C	DIVISION	MSEB MATRUCHHAYA 	KHADKESAWAR ROAD	AURANGABAD	431001',
                '352 -	JALGAON	DY EXE.ENGINEER	MAJOR STORE (A)	DIVISION	MSEB 	M.I.D.C. AREA	 JALGAON		',
                '353 -	RATNAGIRI	EXECUTIVE ENGINEER	O & M	DIVISION	MSEB CHIPLUN 	CHIPLUN		',
                '354 -	SATARA	SUPTDG. ENGINEER	TRANS (O AND M)	CIRCLE	MSEB 	KARAD',
                '355 -	NAGPUR	EXECUTIVE ENGINEER	R.S.& T	DIVISION	MSEB, RECEIVING STAT	SADAR	LINK ROAD	NAGPUR',
                '356 -	THANE	EXECUTIVE ENGINEER	O & M	DIVISION I	NEAR POLICE STATION SHANTI NAGAR	KALYAN ROAD	BHIWANDI',
                '357 -	DHULE	EXECUTIVE ENGINEER	O & M	DIVISION	RURAL DIVISION	SAKRI ROAD	DHULE	424001',
                '358 -	MUMBAI	EXECUTIVE ENGINEER	S & I 	DIVISION	MSEB 	DHARAVI	 MUMBAI	',
                '359 -	PARBHANI	SUPTDG. ENGINEER	O & M	CIRCLE	MSEB,OPP FULE SCHOOL JINTUR ROAD	PARBHANI	431401',
                '360 -	PUNE	EXECUTIVE ENGINEER	H.V.D.C.	DIVISION	NR.PANCHAYAT SAMATI	RAJGURU NAGAR	PUNE	',
                '361 -	AKOLA	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION III	TPS PARAS	VIDYUT NAGAR	PARAS		MSEB',
                '362 -	SOLAPUR	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION LAMBOTI	',
                '363 -	OSMANABAD	EXECUTIVE ENGINEER	MAJOR STORE (A)	DIVISION	POST BOX NO 19	TULJAPUR ROAD	OSMANABAD	413501',
                '364 -	NAGPUR	CHIEF ENGINEER	TRANS (O AND M)	ZONE	OLD POWER HOUSE AREA	MANKAPUR	KORADI ROAD	NAGPUR	440014',
                '365 -	THANE	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	PADGHE',
                '366 -	MUMBAI	EXECUTIVE ENGINEER	O & M	DIVISION	IN FRONT  NRI COMPLE	NERUL	 NAVI  MUMBAI	',
                '367 -	OSMANABAD	EXECUTIVE ENGINEER	O & M	DIVISION	UDAJI BHAVAN	OSMANABAD ROAD	TULJAPUR(BHAVANI)',
                '368 -	NANDED	EXECUTIVE ENGINEER	RURAL	DIVISION	KOTGIRE BLDG	SHAHAJI NAGAR		DEGLOOR	431717',
                '369 -	NASHIK	EXECUTIVE ENGINEER	RURAL	DIVISION	POPHALE BLDG	KANNAD NAKA	 MALEGAON',
                '370 -	CHANDRAPUR	EXECUTIVE ENGINEER	TESTING	DIVISION	VIDYUT BHAVAN	BABUPETH	CHANDRAPUR',
                '371 -	PUNE	EXECUTIVE ENGINEER	O & M	DIVISION	KEDGAON	412203',
                '372 -	MUMBAI	A.P.O GR-I/HR-III	MAHAGENCO	HEAD OFFICE	EXTN.BUILDING,	MATUNGA	DHARAVI ROAD	MUMBAI	400019',
                '373 -	MUMBAI	A.P.O GR-I/HR-III	MAHADISCOM	HEAD OFFICE	P.NO G-9,4TH FLOOR	PRAKASH GADH	BANDRA(EAST)	400051',
                '374 -	MUMBAI	MANAGER(CLAIM)	MAHATRANSCOM	HEAD OFFICE	C-19,IIFL,E BLOCK	PRAKASH GANGA		BANDRA KURLA COMPLEX	400051',
                '375 -	MUMBAI	EXECUTIVE ENGINEER	URBAN	DIVISION	SECT-17,ABHYUDAY BNK	WASHI		NAVI MUMBAI	400708',
                '376 -	BEED	CHIEF GEN.MANAGER	GENERATION (O & M)	THERMAL POWER STATION	NEW PARLI TPS		PARLI-VAIJNATH',
                '377 -	NAGPUR	CHIEF ENGINEER	EHVT CONSTRUCTION	ZONE	INGOLE BHAVAN	ZINGABAI TAKALI	KORADI ROAD	NAGPUR',
                '378 -	MUMBAI	SUPTDG. ENGINEER	TESTING AND COM.	CIRCLE	SECTOR-17,ADM BLDG	WASHI	THANE BELAPUR ROAD	NAVI  MUMBAI	400703',
                '379 -	PUNE	EXECUTIVE ENGINEER	EHVT CONSTRUCTION	DIVISION II	IST FL,ADM.BLDG.925,	KASBA PETH	KUMBHARWADA	411011',
                '380 -	GONDIA	EXECUTIVE ENGINEER	O & M	DIVISION	DEORI',
                '381 -	WARDHA	EXECUTIVE ENGINEER	MAJOR STORE (A)	DIVISION	NEAR 220KV S/S 	BORGAON NAKA	WARDHA	',
                '382 -	NEW MUMBAI	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	GODAVARI BULDG.	BHANDUP	THANE BELAPUR ROAD	BHANDUP	400708	',
                '383 -	PUNE	EXECUTIVE ENGINEER	MAJOR STORE (A)	DIVISION	PLOT NO F/14,MIDC	 BARAMATI	',
                '384 -	THANE	CHIEF ENGINEER	O & M	ZONE	TEJASHRI BLDG	KALYAN (WEST)	KARNIK ROAD	KALYAN (WEST)		',
                '385 -	MUMBAI	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	SECT.06 NR.USTAV SQ.KHARGHAR	NAVI  MUMBAI	410210',
                '386 -	RAIGAD	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	NAGOTHANE	KANSAI		AINGHAR	402126',
                '387 -	PUNE	EXECUTIVE ENGINEER	URBAN	ZONE	PUZ PIMPRI DN	POWER HOUSE CHOWK	 	PUNE	17',
                '388 -	MUMBAI	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION	(EHV) P.BOX  11	AIROLI	THANE BELAPUR ROAD	NAVI  MUMBAI	400708',
                '389 -	PUNE	SUPTDG. ENGINEER	URBAN	CIRCLE	GANESHKHIND	GANESHKHIND	UNIVERCITY ROAD	PUNE	411016',
                '390 -	NASHIK	EXECUTIVE ENGINEER	URBAN	DIVISION	NEAR MASJID	MUKTIDHAM		NASHIK ROAD		',
                '391 -	AKOLA	CHIEF GEN.MANAGER	GENERATION (O & M)	THERMAL POWER STATION	NEW PARAS	VIDYUT NAGAR	PARAS	444109',
                '392 -	RATNAGIRI	EXECUTIVE ENGINEER	MAJOR STORE (A)	DIVISION	ADM BLDG,	NACHANE ROAD	RATNAGIRI	',
                '393 -	RATNAGIRI	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	NEW KOYANA PIMPLI BU	PIMPLI	CHIPLUN	415604',
                '394 -	SATARA	EXECUTIVE ENGINEER	TESTING	DIVISION	KRISHNANAGAR	SOLAPUR ROAD	SATARA	',
                '395 -	JALGAON	SUPTDG. ENGINEER	CIVIL CONSTRUCTION	CIRCLE	CHUMMERY BLDG,BTPS	DEEPNAGAR	  BHUSAWAL	425307',
                '396 -	AKOLA	EXECUTIVE ENGINEER	EHVT CIVIL CONST.	DIVISION	P.NO.3/4,	VIDYA NAGAR	MURTIZAPUR ROAD	AKOLA	444004',
                '397 -	AURANGABAD	SUPTDG. ENGINEER	URBAN	CIRCLE	IST FLR,NEAR ADM BLD	OLD POWER HOUSE	DR.AMBEDKAR ROAD	AURANGABAD	431001',
                '398 -	MUMBAI	SUPTDG. ENGINEER	CONST.CUM MAINT.CIVIL	CIRCLE	PLOT NO G-9,	PRAKASH GADH	BANDRA(EAST)	400005',
                '399 -	THANE	GENERAL MANAGER	O & M	CIRCLE	NR.DHAMANKAR NAKA	  OLD AGRA ROAD	BHIVANDI	421302',
                '400 -	AKOLA	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION IV	PARAS	',
                '401 -	GONDIA	SUPTDG. ENGINEER	O & M	CIRCLE	POWER HOUSE	RAM NAGAR	 GONDIA	441600',
                '402 -	SINDHUDURG	EXECUTIVE ENGINEER	C.C.O & M	DIVISION		BIJLEE NAGAR		KANKAOLI	',
                '403 -	THANE	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	P/31MIDC RES.ZONE 2 	DOMBIWALI	THANE	421203',
                '404 -	JALGAON	EXECUTIVE ENGINEER	EHVT CONSTRUCTION	DIVISION	OLD 132 KV S/S.	M.I.D.C. AREA	AJINTHA ROAD	JALGAON	425003',
                '405 -	PUNE	EXECUTIVE ENGINEER	O & M	DIVISION	SHIVAJI NAGAR DN	SHIVAJI NAGAR	SENPATI BAPAT ROAD	PUNE	410016',
                '406 -	SATARA	EXECUTIVE ENGINEER	GENERATION (O & M)	HYDRO POWER STATION	VIR BHATGHAR	WATER COLONY KHANDALA	',
                '407 -	PUNE	SUPTDG. ENGINEER	URBAN	CIRCLE	I FLOOR ADM.BULD.	RASTA PETH	PUNE	411011	MSEDC LTD.',
                '408 -	AURANGABAD	EXECUTIVE ENGINEER	O & M	DIVISION	VERMA BLDG	CHALISGAON ROAD	KANNAD	',
                '409 -	BEED	SUPTDG. ENGINEER	TRANS (O AND M)	CIRCLE	OLD POWER HOUSE PRE PARLI-VAIJNATH	',
                '410 -	AKOLA	EXECUTIVE ENGINEER	CIVIL CONSTRUCTION	DIVISION V	PARAS	444109	',
                '411 -	SOLAPUR	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	NR.BALE S/S.COMPOUND	AMBIKA NAGAR	BARSHI ROAD	SOLAPUR	413255',
                '412 -	RAIGAD	EXECUTIVE ENGINEER	EHVT CONSTRUCTION	DIVISION	BHINGARI	PANVEL- PUNE HIGHWAY	PANVEL	410206',
                '413 -	CHANDRAPUR	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	HVDC GUEST HOUSE	URJA NAGAR	CHANDRAPUR	',
                '414 -	NASHIK	GENERAL MANAGER	HYDRO POWER STATION	CIRCLE	2/5/3,OPP CGM(O&M) ,EKLAHARE	NASHIK ROAD	422105',
                '415 -	RAIGAD	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	TAKKA COLONYPANVEL	410206',
                '416 -	NASHIK	SUPTDG. ENGINEER	TRANS (O AND M)	CIRCLE	II FL.VIDYUT BHAVAN	 NASHIK ROAD	422101',
                '417 - 	PARBHANI	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	132 KV.S/S.CAMPUS	 JINTUR ROAD	PARBHANI	431401',
                '418 -	NAGPUR	SUPTDG. ENGINEER	EHVT CIVIL CONST.	CIRCLE	III F,VIDHUT BHAVAN	KATOL ROAD	NAGPUR	440013',
                '419 -	PUNE	EXECUTIVE ENGINEER	R.S.& T	DIVISION	III RD FL,ADM BLD	RASTA PETH	PUNE	411011',
                '420 -	AMRAVATI	SUPTDG. ENGINEER	EHV CONSTRUCTION	CIRCLE	NEAR DAFRINE	OLD POWER HOUSE		AMRAVATI',
                '421 -	AKOLA	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	POST.BHUSAR	 APATAPA ROAD	AKOLA	444005',
                '422 -	PUNE	EXECUTIVE DIRECTOR	MAHADISCOM	ZONE	PUNE REGION	  SENPATI BAPAT ROAD	PUNE	411016	',
                '423 -	PUNE	SUPTDG. ENGINEER	TESTING QUALITY ASSURANCE	CIRCLE	BLOCK NO 120,ADM BLD	RASTA PETHPUNE	411011',
                '424 -	AHMEDNAGAR	SUPTDG. ENGINEER	O & M	CIRCLE	NEAR NAGAR COLLEGE	OLD POWER HOUSE	STATION ROAD	AHMEDNAGAR		',
                '425 -	WASHIM	SUPTDG. ENGINEER	O & M	CIRCLE	CIVIL LINES	WASHIM	444505',
                '426 -	LATUR	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	PLOT P-21,132KV S/S	M.I.D.C. AREA	LATUR	413531',
                '427 -	DHULE	SUPTDG. ENGINEER	O & M	CIRCLE	INDIRA GARDEN	ANAND NAGAR	 DEOPUR	424004',
                '428 -	AMRAVATI	SUPTDG. ENGINEER	EHVT CIVIL CONST.	CIRCLE	220KV SUB STN	MORSHI ROAD	AMRAVATI	',
                '429 -	NANDURBAR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	MARKET YARD	NEHRU NAGAR		NANDURBAR	425412',
                '430 -	AURANGABAD	CHIEF ENGINEER	TRANS (O AND M)	ZONE	MILL CORNER		DR.AMBEDKAR ROAD	AURANGABAD	',
                '431 -	PUNE	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	4TH FLR,ADM BLDG	KASBA PETH	PUNE	431011',
                '432 -	NASHIK	EXECUTIVE ENGINEER	O & M	DIVISION	SANCHETI BHAVAN	 DEOLA ROAD	KALWAN	423501',
                '433 -	KOLHAPUR	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	BAPAT COMPLEX	MARKET YARD		KOLHAPUR	416005',
                '434 -	AURANGABAD	SUPTDG. ENGINEER	O & M	CIRCLE	VIDYUT BHAVAN	 	DR.AMBEDKAR ROAD	AURANGABAD	431001',
                '435 -	PUNE	EXECUTIVE ENGINEER	O & M	DIVISION	PARGAON CHOWK	SASWAD	PARGAON ROAD	PURANDAR	',
                '436 -	NASHIK	SUPTDG. ENGINEER	TESTING AND COM.	CIRCLE	3RD FLR,CITY ARCADE	 JAIL ROAD	NASHIK	',
                '437 -	LATUR	SUPTDG. ENGINEER	O & M	CIRCLE	GR.FLR VIDUYT BHAVAN	 SALE GALLI	LATUR	413512	',
                '438 -	BEED	SUPTDG. ENGINEER	O & M	CIRCLE	N.K.PLAZA ADM BLDG	 JALNA ROAD	BEED	431122',
                '439 -	NANDED	EXECUTIVE ENGINEER	URBAN	DIVISION	HINGOLI GATE	VIDYUT BHAVAN	ANNABHAU SATHE SQ	NANDED	',
                '440 - 	MUMBAI	GENERAL MANAGER	MAHAGENCO	HEAD OFFICE	HONKONG BANK BLDG	FORT	M.G.ROAD	MUMBAI	400001',
                '441 -	NAGPUR	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	B/H. C.E.GEN.QTR.	T.P.S.	KHAPERKHEDA	 ',
                '442 -	AKOLA	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	VYAS BHAVAN OPP.HUTATMA SMARK CHOWK	   	AKOLA	',
                '443 -	PUNE	CHIEF ENGINEER	O & M	ZONE	P-34, ABOVE B.O.M	M.I.D.C. AREA	 	BARAMATI		',
                '444 -	THANE	EXECUTIVE DIRECTOR	GENERATION (O & M)	HYDRO POWER STATION	GHATGHAR 		SAHAPUR 	421601',
                '445 -	MUMBAI	GENERAL MANAGER	GENERATION (O & M)	DIVISION	MAHAGUJ COLLIER LTD.	ESTRELLA BATTERIES	LABOUR CAMP ROAD 	MUMBAI	400019',
                '446 -	MUMBAI	EXECUTIVE ENGINEER	O & M	DIVISION	BHANDUP (WEST	ISHWAR NAGAR	L.B.S.ROAD	BHANDUP	',
                '447 -	NAGPUR	CHIEF GEN.MANAGER	GENERATION (O & M)	THERMAL POWER STATION	500MW,	SAUDAMINI BLDG	KHAPERKHEDA	',
                '448 -	THANE	EXECUTIVE ENGINEER	URBAN	DIVISION	OPP GHARDA COLONY,	DOMBIWALI		THANE	421203',
                '449 -	JALGAON	CHIEF ENGINEER	O & M	ZONE	OLD MIDC	VIDYUT BHAVAN	AJINTHA ROAD	JALGAON	425003',
                '450 -	NAGPUR	CHIEF ENGINEER	CONSTRUCTION	THERMAL POWER STATION	KORADI COMPLEX 	CHINDWADA ROAD	NAGPUR	441111',
                '451 -	NANDED	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	II FL. VIDYUT BHAVAN	A.B.CHOWK	NANDED	',
                '452 -	RATNAGIRI	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	SHIVAJI CHOWK	  KHED	415709',
                '453 -	PUNE	SUPTDG. ENGINEER	EHV PROJECT	CIRCLE	BL.405 III FL ADM.BL	RASTA PETH	PUNE	411011	',
                '454 -	NEW MUMBAI	EXECUTIVE ENGINEER	EHV PROJECT	DIVISION	PB 20 AIROLI	KALWA	THANE BELAPUR ROAD	NAVI  MUMBAI	400708',
                '455 -	RAIGAD	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	POST AINGHOR	NAGOTHANE		ROHA	402126',
                '456 -	SATARA	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	ADM.BULD.POST SUPANE	VIJAY NAGAR STATION ROAD	KARAD	415114',
                '457 -	NAGPUR	Sr.Manager(HR)	SPANCO LTD	CIRCLE	3RD FLT,S.K.TOWER	BYRAMJI TOWN	NAGPUR	440013',
                '458 -	AMRAVATI	CHIEF ENGINEER	TRANS (O AND M)	ZONE	NEAR DAFFRIN	OLD POWER HOUSE	SHRIKRISHNA PETH	AMRAVATI	',
                '459 -	THANE	EXECUTIVE ENGINEER	C.C.O & M	DIVISION II	III FLR,NEW ADM BLDG	WAGLE ESTATE	NEAR PASSPORT OFFICE	THANE(WEST) 400604',
                '460 -	RATNAGIRI	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	KOYANA	',
                '461 -	NASHIK	EXECUTIVE ENGINEER	O & M	DIVISION	CAMP 2 AREA	 YEWLA ROAD	MANMAD	423104',
                '462 -	AHMEDNAGAR	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	SHRIRAMPUR	413709',
                '463 -	NANDED	EXECUTIVE ENGINEER	EHV CONSTRUCTION	DIVISION	132KV S/S CAMPUS	JANGAMWADI	NANDED	',
                '464 -	DHULE	SUPTDG. ENGINEER	O & M	CIRCLE	PL. 8, SAHADRI BULD.	ANAND NAGAR		DEOPUR	424002	',
                '465 -	LATUR	EXECUTIVE ENGINEER	O & M	DIVISION	NILANGA	',
                '466 -	RAIGAD	DY.CHIEF ENGINEER(CIVIL)	GENERATION ( PROJECT)	PROJECT	1220MW EXPANSION	URAN	',
                '467 -	THANE	SUPTDG. ENGINEER	O & M	CIRCLE	URBAN,NEW ADM BLDG	WAGLE ESTATE	THANE	400604	',
                '468 -	AHMEDNAGAR	EXECUTIVE ENGINEER	O & M	DIVISION	URBAN DIVISION		KARJAT		',
                '469 -	AHMEDNAGAR	EXECUTIVE ENGINEER	RURAL	DIVISION	OLD POWER HOUSE	 	AHMEDNAGAR	',
                '470 -	MUMBAI	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION	IIND FLR,NR ASIAN PA	VIDYUT BHAVAN	L.B.S.ROAD	BHANDUP	400078',
                '471 -	JALNA	SUPTDG. ENGINEER	O & M	CIRCLE	CHANAKY COMPLEX	KANAIHYA NAGAR	DEULGAON RAJA ROAD	JALNA	431203	',
                '472 -	AKOLA	EXECUTIVE ENGINEER	EHV CONSTRUCTION	DIVISION	TYPE-II-1	M.E.S.B.COLONY	GORAKSHAN ROAD	AKOLA	444004',
                '473 -	PUNE	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	III RD FLR,41/50,	WADHWANI PLAZA	PIMPRI CHINCHWAD	411018',
                '474 -	SANGLI	SUPTDG. ENGINEER	O & M	CIRCLE	VISHAMBAGH SANGLI	416416',
                '475 -	PUNE	SUPTDG. ENGINEER	CIVIL	CIRCLE	PL NO 302,IIND FLR	RASTA PETH	PUNE',
                '476 -	PUNE	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION I	B.NO.406, III FL.ADM	RASTA PETH	PUNE',
                '477 -	DHULE	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	132 KV S/S COLONY	 	MUMBAI AGRA ROAD	DHULE',
                '478 -	PUNE	SUPTDG. ENGINEER	CIVIL	CIRCLE	BLOCK407 II FL.	RASTA PETH PUNE	11',
                '479 -	NANDED	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	WORKSHOP CORNER	JANGAMWADI	NANDED	431605',
                '480 -	HINGOLI	SUPTDG. ENGINEER	O & M	CIRCLE	HINGOL',
                '481 -	PUNE	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	DSK PRIDE 1 FLOOR		MANCHAR	410503',
                '482 -	PUNE	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	LONIKHAND	SAMBHAJI NAGAR	HAVELI 	412216',
                '483 -	DHULE	SUPTDG. ENGINEER	CIVIL CONSTRUCTION	CIRCLE	PLOT NO.3  	ASHOK NAGAR		DHULE	 ',
                '484 -	PUNE	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	JEJURIPURANDAR	412303',
                '485 -	CHANDRAPUR	EXECUTIVE ENGINEER	EHV CONSTRUCTION	DIVISION	B/H.66 KV SUBSTATION	SHASTRI NAGAR	MUL ROAD	CHANDRAPUR',
                '486 -	NASHIK	SUPTDG. ENGINEER	URBAN	CIRCLE	MADHUMILAN LOGDGE BL	SOMWARI PETH 	NASHIK',
                '487 -	JALNA	EXECUTIVE ENGINEER	O & M	DIVISION	MASTGAD	 	DARGA ROAD	JALNA	431203',
                '488 -	PUNE	EXECUTIVE ENGINEER	O & M	DIVISION	PARVATI DN.SINGHAGAD ROAD	PUNE	411030',
                '489 -	SOLAPUR	EXECUTIVE ENGINEER	O & M	DIVISION	NR.OLD POLICE STATIO	AKLUJ 	413101',
                '490 -	RAIGAD	EXECUTIVE ENGINEER	TRAINING	DIVISION	SHIKSAK COLONYANTURA ROAD	PEN	402107',
                '491 -	KOLHAPUR	EXECUTIVE ENGINEER	O & M	DIVISION	APP.ZELE HIGH SCHOOL	URJA NAGAR	SHIRSOLI ROAD	JAYSINGPUR',
                '492 -	PUNE	SUPTDG. ENGINEER	O & M	CIRCLE	URJA BHAVAN	M.I.D.C. AREA	BHIGWAN ROAD	BARAMATI	413102	',
                '493 -	RAIGAD	EXECUTIVE ENGINEER	O & M	DIVISION	NAGAR PARISAD BLDG. ROHA	402109',
                '494 -	NASHIK	SUPTDG. ENGINEER	EHVT CIVIL CONST.	CIRCLE	ADM BLD.II FL.JAIL ROAD	NASHIK ROAD',
                '495 -	PUNE	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	P-10 MIDC PHASE III	CHAKAN	410501	',
                '496 -	PUNE	EXECUTIVE ENGINEER	O & M	DIVISION	221,NR.TALERA PARK S	KALYANI NAGAR		PUNE	411006',
                '497 -	SATARA	SUPTDG. ENGINEER	O & M	CIRCLE	I FLOOR VIDYUTBHABAN	KRISHNANAGAR	SATARA	415003',
                '498 -	PUNE	EXECUTIVE ENGINEER	O & M	DIVISION	NR.PIMPRI CHINC.M.C.	BALAJI NAGAR	TELCO ROAD	BHOSARI	26',
                '499 -	PUNE	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	APP.P.C.M.C. SCHOOL	PIMPRI CHINCHWAD	411017',
                '500 -	CHANDRAPUR	CHIEF ENGINEER	O & M	ZONE	VIDYUT BHAVAN IIFL	BABUPETH	CHANDRAPUR	',
                '501 -	NAGPUR	EXECUTIVE ENGINEER	RURAL	DIVISION	3/4,ASHTWINAYK SNKUL	GANPATI NAGAR	NAGPUR ROAD	UMRED	441203',
                '502 -  KOLHAPUR	CHIEF ENGINEER	O & M	ZONE	TARABAI PARK	VIDYUT BHAVAN		KOLHAPUR	03',
                '503 -	GONDIA	CHIEF ENGINEER	O & M	ZONE	PLD POWER HOUSE 	RAM NAGAR		GONDIA	',
                '504 -	MUMBAI	Sr.Manager(HR)	INFRASTRUCTURE	DEPARTMENT	7 FL .BANDRA KU.COM 	BANDRA (EAST)		MUMBAI	400051',
                '505 -	SATARA	EXECUTIVE ENGINEER	TELECOM	DIVISION	SUPANE	VIJAY NAGAR STATION ROAD	KARAD	411014',
                '506 -	PUNE	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	URJA BHAVAN	 BHIGWAN ROAD	BARAMATI	413102',
                '507 -	YEOTMAL	EXECUTIVE ENGINEER	TRANS (O AND M)	DIVISION	IV, FL.UDYOG BHAVAN		DARWHA ROAD	YEOTMAL	445001	',
                '508 -	NAGPUR	REGIONAL DIRECTOR	MAHADISCOM	ZONE	VIDYUT BHAVAN	 	KATOL ROAD	NAGPUR	',
                '509 -	JALGAON	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	KATE BUILDING	MUKTAI NAGAR	BODWAD ROAD	MUKTAI NAGAR	425306',
                '510 -	AKOLA	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	SHIVKRUPA NR.CANARA POPATKHED ROAD	AKOT 	444001',
                '511 -	AURANGABAD	SUPTDG. ENGINEER	TRANS (O AND M)	CIRCLE	JUBILE PARK,	AURANGABAD		',
                '512 -	AURANGABAD	REGIONAL DIRECTOR	MAHADISCOM	ZONE	VIDYUT BHAVAN MILL CORNER	DR.AMBEDKAR ROAD	AURANGABAD	431001',
                '513 -	KOLHAPUR	SUPTDG. ENGINEER	TRANS (O AND M)	CIRCLE	BAPAT CAMP	KOLHAPUR		',
                '514 -	SOLAPUR	EXECUTIVE ENGINEER	EHV PROJECT	DIVISION III	132 KV NAIWAS S/S.	MILL COMPOUND 	   	SOLAPUR	413001',
                '515 -	BHANDARA	EXECUTIVE ENGINEER	TESTING	DIVISION	VIDYUT BHAVAN	 AGPUR ROAD	BHANDARA	',
                '516 -	NANDURBAR	SUPTDG. ENGINEER	O & M	CIRCLE	INDIRAGANDHI BUSNES GIRI VIHAR	NANDURBAR	425412',
                '517 -	PUNE	REGIONAL DIRECTOR	MEDA	UNIT	2 FL.MHADA C.COMPLEX	YERWADA		PUNE	411006	',
                '518 -	CHANDRAPUR	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION II	NR.AUNDA GATE	URJA NAGAR	CHANDRAPUR	442404',
                '519 -	PARBHANI	EXECUTIVE ENGINEER	C.C.O & M	DIVISION II	VIDYUT BHAVAN	 JINTUR ROAD	PARBHANI	431401	',
                '520 -	RAIGAD	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	KRUSHKUTIR 	PANT NAGAR	ALIBAG	402201',
                '521 -	THANE	EXECUTIVE ENGINEER	TESTING	DIVISION	ADM.BLD.4 FL.APP.PAS	WAGLE ESTATE	THANE	400604',
                '522 -	AURANGABAD	EXECUTIVE ENGINEER	RURAL	DIVISION II	VIDYUT BHAVAN	DR.AMBEDKAR ROAD	AURANGABAD	',
                '523 -	THANE	EXECUTIVE ENGINEER	O & M	DIVISION	VIDYUT BHAVAN MULUND	MUMBAI	',
                '524 -	AURANGABAD	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	132 K.V.S/S. PREMISE	SHAHAJI NAGAR	JALGAON ROAD	SILLOD 	431112',
                '525 -	AHMEDNAGAR	EXECUTIVE ENGINEER	400 KV R.S.	DIVISION	GAT NO 31 DEULWADI	KARJAT	414403	',
                '526 -	PARBHANI	EXECUTIVE ENGINEER	CONST.CUM MAINT.CIVIL	DIVISION OLD POWER HOUSE	JINTUR ROAD	PARBHANI	431401',
                '527 -	PUNE	EXECUTIVE ENGINEER	O & M	DIVISION	MULSI DIVISION PUNE',
                '528 -	YEOTMAL	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	VIDYUT BHAVAN	 DARWHA',
                '529 -	SINDHUDURG	SUPTDG. ENGINEER	C.C.O & M	CIRCLE	VIDYUT BHAVAN	 SINDHUDURG',
                '530 -	SANGLI	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	VIDYUT BHAVAN	 ISLAMPUR 415409',
                '531 -	PUNE	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	VIDYUT BHAVAN	MANCHAR	410503	',
                '532 -	SANGLI	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	VIDYUT BHAVAN	 VITA 	415311',
                '533 -	NANDED	EXECUTIVE ENGINEER	C.C.O & M	DIVISION	VIDYUT BHAVAN NANDED',
                '534 -	BULDHANA	EXECUTIVE ENGINEER	O & M	DIVISION	VIDYUT BHAVAN MEHKAR	443301',

              ], (val) => setState(() => division = val), isRequired: true),
              buildTextField(billNoController, 'Bill No.', true),
              buildDateField(joiningDateController, 'Company Joining Date (dd-mm-yyyy)', true),
              buildTextField(cpfNoController, 'CPF No.', true),
              buildTextField(sapIdController, 'Sap Id.', false),

              // Bank
              sectionTitle("Bank Details"),
              buildTextField(accountNameController, 'Name on Account', true),
              buildTextField(accountNoController, 'Account No.', true),
              buildTextField(bankNameController, 'Bank Name', true),
              buildTextField(branchController, 'Branch', true),
              buildTextField(ifscController, 'IFSC Code', true),

              // Nominees
              sectionTitle("Nominee 1 Details"),
              buildTextField(nominee1NameController, 'Nominee Name1', true),
              buildDropdown("Nominee Relation1", nominee1Relation, ['Spouse', 'Parent', 'Sibling', 'Other'], (val) => setState(() => nominee1Relation = val), isRequired: true),
              buildDateField(nominee1DOBController, 'Nominee DOB1 (dd-mm-yyyy)', true),

              sectionTitle("Nominee 2 Details"),
              buildTextField(nominee2NameController, 'Nominee Name2', false),
              buildDropdown("Nominee Relation2", nominee2Relation, ['Spouse', 'Parent', 'Sibling', 'Other'], (val) => setState(() => nominee2Relation = val)),
              buildDateField(nominee2DOBController, 'Nominee DOB2 (dd-mm-yyyy)', false),

              // Current Address
              sectionTitle("Current Address"),
              buildTextField(currentHouseController, 'House No.', true),
              buildTextField(currentLocalityController, 'Locality', true),
              buildTextField(currentLandmarkController, 'Landmark', true),
              buildTextField(currentRoadController, 'Road', true),
              buildTextField(currentAreaController, 'Area', true),
              buildTextField(currentPostOfficeController, 'Post Office', true),
              buildTextField(currentCityController, 'City/Tahsil', true),
              buildTextField(currentDistrictController, 'District', true),
              buildDropdown("State", currentState, ['Andhra Pradesh', 'Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat',
                'Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland',
                'Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal'
              ], (val) => setState(() => currentState = val), isRequired: true),
              buildTextField(currentPincodeController, 'Pincode', true, keyboardType: TextInputType.number),

              CheckboxListTile(
                title: Text("Check this box if both addresses are the same."),
                value: isAddressSame,
                onChanged: (val) {
                  setState(() {
                    isAddressSame = val!;
                    if (isAddressSame) copyAddress();
                  });
                },
              ),

              // Permanent Address
              sectionTitle("Permanent Address"),
              buildTextField(permanentHouseController, 'House No.', true),
              buildTextField(permanentLocalityController, 'Locality', true),
              buildTextField(permanentLandmarkController, 'Landmark', true),
              buildTextField(permanentRoadController, 'Road', true),
              buildTextField(permanentAreaController, 'Area', true),
              buildTextField(permanentPostOfficeController, 'Post Office', true),
              buildTextField(permanentCityController, 'City/Tahsil', true),
              buildTextField(permanentDistrictController, 'District', true),
              buildDropdown("State", permanentState, ['Andhra Pradesh', 'Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat',
                'Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland',
                'Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal'], (val) => setState(() => permanentState = val), isRequired: true),
              buildTextField(permanentPincodeController, 'Pincode', true, keyboardType: TextInputType.number),
              SizedBox(height: 20),
              ElevatedButton(
                onPressed: () {
                  if (_formKey.currentState!.validate()) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(content: Text('Form Submitted Successfully!')),
                    );
                  }
                },
                child: Text('Submit'),
              )
            ],
          ),
        ),
      ),
    );
  }

  // Reusable widget methods
  Widget sectionTitle(String title) => Padding(
    padding: const EdgeInsets.symmetric(vertical: 12.0),
    child: Text(title, style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
  );

  Widget buildTextField(TextEditingController controller, String label, bool isRequired, {TextInputType keyboardType = TextInputType.text}) =>
      Padding(
        padding: const EdgeInsets.only(bottom: 12.0),
        child: TextFormField(
          controller: controller,
          decoration: InputDecoration(labelText: label, border: OutlineInputBorder()),
          keyboardType: keyboardType,
          validator: isRequired ? (value) => value == null || value.trim().isEmpty ? '$label is required' : null : null,
        ),
      );

  Widget buildPasswordField(TextEditingController controller, String label) =>
      Padding(
        padding: const EdgeInsets.only(bottom: 12.0),
        child: TextFormField(
          controller: controller,
          obscureText: true,
          decoration: InputDecoration(labelText: label, border: OutlineInputBorder()),
          validator: (value) {
            if (value == null || value.trim().isEmpty) return '$label is required';
            if (label == "Confirm Password" && value != passwordController.text) return "Passwords do not match";
            return null;
          },
        ),
      );

  Widget buildDropdown(String label, String? value, List<String> items, ValueChanged<String?> onChanged, {bool isRequired = false}) =>
      Padding(
        padding: const EdgeInsets.only(bottom: 12.0),
        child: DropdownButtonFormField<String>(
          value: value,
          items: items.map((val)
          => DropdownMenuItem(value: val, child: SizedBox(
              width: MediaQueryData.fromView(WidgetsBinding.instance.window).size.width*0.8,
              child: Text(
                //textAlign: TextAlign.right,
                val,
                overflow: TextOverflow.ellipsis,
                maxLines: 4,
                softWrap: false,
              )))).toList(),
          onChanged: onChanged,
          decoration: InputDecoration(labelText: label, border: OutlineInputBorder()),
          validator: isRequired ? (value) => value == null || value.isEmpty ? 'Please select $label' : null : null,
        ),
      );

  Widget buildDateField(TextEditingController controller, String label, bool isRequired) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12.0),
      child: TextFormField(
        controller: controller,
        readOnly: true,
        decoration: InputDecoration(
          labelText: label,
          border: OutlineInputBorder(),
          suffixIcon: Icon(Icons.calendar_today),
        ),
        validator: isRequired
            ? (value) => value == null || value.trim().isEmpty ? '$label is required' : null
            : null,
        onTap: () async {
          FocusScope.of(context).requestFocus(FocusNode()); // Prevents keyboard from appearing
          final DateTime? picked = await showDatePicker(
            context: context,
            initialDate: DateTime.now(),
            firstDate: DateTime(1900),
            lastDate: DateTime(2100),
          );
          if (picked != null) {
            controller.text = "${picked.day.toString().padLeft(2, '0')}-${picked.month.toString().padLeft(2, '0')}-${picked.year}";
          }
        },
      ),
    );
  }

}
